spring.application.name=ticketbookingsystem

#spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.oalvlvqblzjjpxtvtkpl
spring.datasource.password=dSVx85BtIR8DSAjc
spring.datasource.driverClassName=org.postgresql.Driver

## HikariCP - safe for transaction mode
#spring.datasource.hikari.maximum-pool-size=15
#spring.datasource.hikari.minimum-idle=0
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.max-lifetime=1800000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.enabled=true
server.servlet.session.timeout=-1