spring.application.name=ticketbookingsystem

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.oalvlvqblzjjpxtvtkpl
spring.datasource.password=dSVx85BtIR8DSAjc
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.enabled=true
server.servlet.session.timeout=-1